/** Offline: nenhuma chamada ao fornecedor, credencial fictícia somente nos testes. */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { buildSelsynRequest, coordinatesValid, localDateToUtc, mapTrackedVehicle, providerError, sanitizeSelsyn, SELSYN_OPERATIONS, SelsynError, trackingId, trackingTotals, validateSelsynResponse } from "../src/lib/selsyn";
import { fetchSelsyn, getSelsynCommandExecution, getSelsynCommandFromHistory, sendSelsynCommand } from "../src/lib/server/selsyn-transport";
import { assertCommandExecution, validImei, validateLockSafety } from "../src/lib/selsyn-command";
import { requireCommandOrigin } from "../src/lib/server/selsyn-command";
import { authenticatePortal, parsePortalSession, portalAuthorization } from "../src/lib/server/selsyn-session";
import { capabilityMatrix, integrationStatus, supportReport, type SelsynProbe } from "../src/lib/selsyn-capabilities";

const dates = { dataInicial: "2026-10-01T00:00:00.000Z", dataFinal: "2026-10-01T01:00:00.000Z" };
assert.equal(Object.keys(SELSYN_OPERATIONS).length, 53);
assert.equal(Object.values(SELSYN_OPERATIONS).filter(o => o.group === "Integração Consulta Nível Cliente - V1").length, 34);
const sensor = buildSelsynRequest("relatorioHistoricoSensor", { ...dates, idRastreavel: "123" });
assert.equal(sensor.path, "/relatorio/sensor/historico/123"); assert.equal(sensor.query.get("format"), "JSON");
const detailed = buildSelsynRequest("relatorioSensorDetalhado", { ...dates, idRastreavel: "123", sensorId: "7", format: "XLSX" });
assert.equal(detailed.path, "/relatorio/sensor/detalhado/123/7"); assert.equal(detailed.query.get("sensorId"), "7");
for (const input of [{ ...dates, idRastreavel: "0" }, { ...dates, idRastreavel: "123", url: "https://example.com" }, { ...dates, idRastreavel: "123", format: "CSV" }, { ...dates, dataInicial: "2026-02-30T00:00:00.000Z", idRastreavel: "1" }, { ...dates, dataFinal: "2026-09-30T00:00:00.000Z", idRastreavel: "1" }]) assert.throws(() => buildSelsynRequest("relatorioHistoricoSensor", input), SelsynError);
assert.throws(() => buildSelsynRequest("bloqueio", {}));
assert.throws(() => buildSelsynRequest("gdrFindRastreavelPorIdentificador", { identificador: "../secret" }));
assert.throws(() => buildSelsynRequest("__proto__", {}));
assert.throws(() => buildSelsynRequest("relatorioTotalizador", { ...dates, rastreavel: "1" }));
assert.equal(trackingId("9223372036854775807"), "9223372036854775807");
assert.equal(trackingId("9223372036854775808"), null); assert.equal(trackingId(9007199254740992), null);
assert.ok(coordinatesValid(0, 0)); assert.ok(!coordinatesValid(91, 0)); assert.ok(!coordinatesValid(null, 0));
assert.equal(localDateToUtc("2026-10-01T12:00"), new Date(2026, 9, 1, 12, 0).toISOString());
assert.throws(() => localDateToUtc("2026-02-30T12:00"));
const r = mapTrackedVehicle({ id: 123, identificador: "ABC1D23", offLine: false, ultimaPosicao: { latitude: 0, longitude: 0, speed: 0, ignition: false, battery: 0 }, ultimaAtualizacaoSensor: [{ id: 7, value: "0", description: "Sensor de teste" }] });
assert.equal(r.position?.ignition, false); assert.equal(r.battery, 0);
assert.deepEqual(trackingTotals([r, { ...r, id: "2", offline: true }]), { tracked: 2, moving: 0, stopped: 1, offline: 1, unknown: 0 });
assert.deepEqual(validateSelsynResponse("gdrAovivo", []), []);
assert.throws(() => validateSelsynResponse("gdrAovivo", { wrong: true }));
assert.throws(() => validateSelsynResponse("aovivoPorRastreavel", { id: 9007199254740992 }));
assert.throws(() => validateSelsynResponse("aovivoPorRastreavel", { offLine: "false" }));
assert.equal(validateSelsynResponse("relatorioHistoricoSensor", null), null);
const secret = "credential-for-offline-test";
const clean = sanitizeSelsyn({ token: secret, content: { url: `https://example.com/?x-api-key=${secret}`, text: secret } }, secret);
assert.ok(!JSON.stringify(clean).includes(secret)); assert.ok(!JSON.stringify(clean).includes('"token"'));
const responseFetch = (res: Response): typeof fetch => (async () => res) as typeof fetch;
let calls = 0;
const fake: typeof fetch = (async (url: string | URL | Request, init?: RequestInit) => {
  calls++;
  const u = new URL(String(url));
  assert.equal(u.origin, "https://api.appselsyn.com.br");
  assert.equal(u.pathname, "/keek/rest/relatorio/sensor/historico/123");
  assert.equal(u.searchParams.get("x-api-key"), null, "chave fora da URL");
  assert.equal(new Headers(init?.headers).get("x-api-key"), secret, "chave no header (comportamento real da API)");
  assert.equal(init?.method, "GET"); assert.equal(init?.redirect, "error"); assert.equal(init?.cache, "no-store");
  assert.ok(init?.signal);
  return Response.json({ content: { rows: [], echo: secret }, id: 1, status: { key: "TEST", value: "Teste offline" } });
}) as typeof fetch;
const fetched = await fetchSelsyn("relatorioHistoricoSensor", { ...dates, idRastreavel: "123" }, secret, fake);
assert.equal(calls, 1); assert.ok(!JSON.stringify(fetched).includes(secret));
for (const status of [400, 401, 403, 404, 429, 500]) {
  await assert.rejects(fetchSelsyn("relatorioHistoricoSensor", { ...dates, idRastreavel: "123" }, secret, responseFetch(new Response(secret, { status }))), e => e instanceof SelsynError && !e.message.includes(secret) && e.code === providerError(status).code);
}
await assert.rejects(fetchSelsyn("relatorioHistoricoSensor", { ...dates, idRastreavel: "123" }, "", fake), e => e instanceof SelsynError && e.code === "NOT_CONFIGURED");
const timeout: typeof fetch = (async () => { throw new DOMException(`Timeout ${secret}`, "TimeoutError"); }) as typeof fetch;
await assert.rejects(fetchSelsyn("relatorioHistoricoSensor", { ...dates, idRastreavel: "123" }, secret, timeout), e => e instanceof SelsynError && e.code === "TIMEOUT" && !e.message.includes(secret));
await assert.rejects(fetchSelsyn("gdrAovivo", {}, secret, responseFetch(new Response("<html>err</html>"))), e => e instanceof SelsynError && e.code === "INVALID_PROVIDER_RESPONSE");
assert.equal((await fetchSelsyn("gdrAovivo", {}, secret, responseFetch(new Response(null, { status: 204 })))).data, null);
const pdf = await fetchSelsyn("relatorioHistoricoSensor", { ...dates, idRastreavel: "123", format: "PDF_PORTRAIT" }, secret, responseFetch(new Response("%PDF-offline-fixture", { headers: { "content-type": "application/pdf" } })));
assert.ok(pdf.file?.name.endsWith(".pdf"));
await assert.rejects(fetchSelsyn("relatorioHistoricoSensor", { ...dates, idRastreavel: "123", format: "HTML" }, secret, responseFetch(new Response(`<html>${secret}</html>`, { headers: { "content-type": "text/html" } }))), e => e instanceof SelsynError && e.code === "UNSAFE_EXPORT");
// Catálogo não contém operações de escrita; guardas nas rotas e na migration estão presentes.
for (const op of Object.values(SELSYN_OPERATIONS)) assert.ok(!/intervencao|bloqueio|desbloqueio|saida\/ativar/.test(op.path));
for (const p of ["status/route.ts", "fleet/route.ts", "link/route.ts", "query/[operationId]/route.ts"]) assert.ok(readFileSync(`src/app/api/selsyn/${p}`, "utf8").includes("await selsynStaff()"));
assert.ok(readFileSync("src/app/api/selsyn/diagnostic/route.ts", "utf8").includes(`requireStaff("integrations")`), "diagnóstico só para quem gerencia integrações");
for (const p of ["fleet/route.ts", "link/route.ts", "diagnostic/route.ts"]) {
  const src = readFileSync(`src/app/api/selsyn/${p}`, "utf8");
  const auth = Math.max(src.indexOf("await selsynStaff()"), src.indexOf("await requireStaff("));
  assert.ok(auth > 0 && src.indexOf("assertSelsynTenant()") > auth, `${p}: tenant checado depois de definir a locadora (senão 500)`);
}
assert.ok(readFileSync("src/lib/server/selsyn.ts", "utf8").includes("assertSelsynTenant();"), "querySelsyn fail-closed fora da locadora dona");
assert.ok(!readFileSync("src/app/api/selsyn/fleet/route.ts", "utf8").includes("gdrAovivo"), "frota não depende de GDR");
assert.ok(readFileSync("src/app/api/selsyn/query/[operationId]/route.ts", "utf8").includes("VEHICLE_SCOPE_REQUIRED"), "consulta exige rastreável vinculado");
assert.ok(readFileSync("supabase/migrations/20261018000000_selsyn_readonly_guard.sql", "utf8").includes("vehicles_selsyn_link_guard"), "vínculo só pelo backend");

// ---------- Erros: 401 ≠ 403 ≠ 404 ≠ 429 ≠ 5xx ----------
assert.equal(providerError(401).code, "AUTHENTICATION_FAILED");
assert.equal(providerError(403).code, "PROVIDER_FORBIDDEN");
assert.equal(providerError(404).code, "PROVIDER_NOT_FOUND");
assert.equal(providerError(429).code, "PROVIDER_RATE_LIMITED"); assert.equal(providerError(429).retryable, true);
assert.equal(providerError(503).code, "PROVIDER_UNAVAILABLE"); assert.equal(providerError(503).retryable, true);
assert.equal(providerError(403).retryable, false); assert.equal(providerError(401).retryable, false);
await assert.rejects(fetchSelsyn("aovivo", {}, secret, responseFetch(new Response(JSON.stringify({ message: "Acesso negado", key: secret }), { status: 403, headers: { "content-type": "application/json" } }))), e => e instanceof SelsynError && JSON.stringify(e.diagnostics?.providerBody).includes("Acesso negado") && !JSON.stringify(e.diagnostics).includes(secret));
// Contrato oficial salvo: operações do catálogo existem com mesmo método/path; as 4 sondas usam api-key-cliente (x-api-key na query).
const spec = JSON.parse(readFileSync("docs/vendor/selsyn/openapi.json", "utf8"));
assert.equal(spec.components.securitySchemes["api-key-cliente"].in, "query"); assert.equal(spec.components.securitySchemes["api-key-cliente"].name, "x-api-key");
const specOps = new Map<string, { method: string; path: string; security: Record<string, unknown>[] }>();
for (const [path, methods] of Object.entries(spec.paths as Record<string, Record<string, { operationId?: string; security?: Record<string, unknown>[] }>>)) for (const [method, o] of Object.entries(methods)) if (o?.operationId) specOps.set(o.operationId, { method, path, security: o.security ?? [] });
for (const [id, op] of Object.entries(SELSYN_OPERATIONS)) { const s = specOps.get(id); assert.ok(s, `${id} ausente no OpenAPI`); assert.equal(s!.method, "get", id); assert.equal(s!.path, op.path, id); assert.ok(s!.security.some(x => "api-key-cliente" in x), `${id} aceita api-key-cliente`); }
assert.equal(specOps.get("gdrActivateOutput")?.method, "put"); assert.ok(!Object.hasOwn(SELSYN_OPERATIONS, "gdrActivateOutput"), "comando fora do catálogo");
await assert.rejects(fetchSelsyn("gdrAovivo", {}, secret, responseFetch(new Response("{}", { status: 403, headers: { "content-type": "application/json", "x-request-id": "req-123" } }))), e => e instanceof SelsynError && e.diagnostics?.httpStatus === 403 && e.diagnostics.requestId === "req-123" && e.diagnostics.pathname === "/keek/rest/v1/integracao/gdr/posicao/aovivo" && !JSON.stringify(e.diagnostics).includes(secret));

// ---------- Matriz de capabilities: parcial, sem herdar permissões não testadas ----------
const probe = (operation: string, ok: boolean, httpStatus: number | null, code = ok ? "OK" : "PROVIDER_FORBIDDEN"): SelsynProbe => ({ operation, label: operation, group: SELSYN_OPERATIONS[operation].group, ok, code, httpStatus });
const partial = [probe("aovivo", true, 200), probe("integracaoAoVivo", true, 200), probe("intergacaoListTipoAlerta", false, 403), probe("gdrAovivo", false, 403)];
const matrix = capabilityMatrix(partial);
assert.equal(matrix.find(c => c.id === "SELSYN_READ_POSITION")?.status, "AVAILABLE");
assert.equal(matrix.find(c => c.id === "SELSYN_READ_GDR")?.status, "FORBIDDEN");
assert.equal(matrix.find(c => c.id === "SELSYN_READ_HISTORY")?.status, "UNKNOWN", "histórico não testado continua desconhecido");
assert.equal(integrationStatus(true, partial), "CONNECTED_PARTIAL");
assert.equal(integrationStatus(true, partial.map(p => ({ ...p, ok: false, httpStatus: 403, code: "PROVIDER_FORBIDDEN" }))), "FORBIDDEN");
assert.equal(integrationStatus(true, [probe("aovivo", false, 401, "AUTHENTICATION_FAILED")]), "AUTH_ERROR");
assert.equal(integrationStatus(true, []), "CONFIGURED");
assert.equal(integrationStatus(false, partial), "NOT_CONFIGURED");
const report = supportReport(partial, "teste", "2026-10-06T00:00:00.000Z");
assert.ok(report.includes("gdrAovivo") && report.includes("HTTP 403") && report.includes("NÃO EXECUTADOS"));
assert.ok(!/x-api-key=|SELSYN_API_KEY=/.test(report), "relatório nunca carrega credencial");
const sql = readFileSync("supabase/migrations/20261007000000_selsyn_tracking.sql", "utf8");
assert.ok(sql.includes("pg_advisory_xact_lock")); assert.ok(sql.includes("enable row level security")); assert.ok(sql.includes("from public,anon,authenticated"));
// PDF em base64 dentro de content: o formato real de Situação atual.
const encodedPdf = Buffer.from("%PDF-1.7\n" + "fixture ".repeat(30)).toString("base64");
const embedded = await fetchSelsyn("relatorioSituacaoAtual", { idRastreavel: "123" }, secret, responseFetch(Response.json({ content: encodedPdf, status: { key: "SUCCESS" } })));
assert.equal(embedded.file?.mime, "application/pdf");
assert.equal(Buffer.from(embedded.file!.base64, "base64").subarray(0, 5).toString(), "%PDF-");
const leakingPdf = Buffer.from("%PDF-1.7\n" + secret + "fixture ".repeat(30)).toString("base64");
await assert.rejects(fetchSelsyn("relatorioSituacaoAtual", { idRastreavel: "123" }, secret, responseFetch(Response.json({ content: leakingPdf }))), e => e instanceof SelsynError && e.code === "UNSAFE_EXPORT");
assert.deepEqual(mapTrackedVehicle({ id: 123, identificador: "ABC1D23", bloqueioHabilitado: true, lock: false }).lockEnabled, true);
const commandRoute = readFileSync("src/app/api/selsyn/command/route.ts", "utf8");
assert.ok(commandRoute.includes("COMMANDS_DISABLED"));
assert.ok(commandRoute.indexOf("await reauthenticateCommand(userId, body.password)") < commandRoute.indexOf("await sendSelsynCommand"));
assert.ok(commandRoute.includes("reserve_selsyn_command"));
assert.ok(commandRoute.includes("validateLockSafety"));
assert.ok(readFileSync("src/app/api/selsyn/status/route.ts", "utf8").includes('process.env.SELSYN_COMMANDS_ENABLED === "true"'));
assert.ok(validImei("866557080755830"));
assert.ok(!validImei("866557080755831") && !validImei("866557080755830LW4G"));
assert.throws(() => requireCommandOrigin(new Request("https://example.com/api/selsyn/command")));
assert.throws(() => requireCommandOrigin(new Request("https://example.com/api/selsyn/command", { headers: { origin: "https://other.example" } })));
assert.doesNotThrow(() => requireCommandOrigin(new Request("https://example.com/api/selsyn/command", { headers: { origin: "https://example.com" } })));
let puts = 0;
const fakePut: typeof fetch = (async (url: string | URL | Request, init?: RequestInit) => {
  puts++;
  assert.equal(init?.method, "PUT");
  assert.equal(new URL(String(url)).pathname, "/keek/rest/v1/integracao/gdr/bloqueio/ABC1D23/866557080755830");
  assert.equal(new Headers(init?.headers).get("x-api-key"), secret);
  assert.equal(init?.redirect, "error");
  assert.equal(new URL(String(url)).search, "");
  return Response.json({ id: 123, status: { key: "PENDING" }, returnDate: null, usuario: "não deve sair" });
}) as typeof fetch;
assert.deepEqual(await sendSelsynCommand("lock", "ABC1D23", "866557080755830", secret, fakePut), { id: "123", status: "PENDING", returnedAt: null, deviceId: null });
assert.equal(puts, 1);
let timeouts = 0;
await assert.rejects(sendSelsynCommand("unlock", "ABC1D23", "866557080755830", secret, (async () => { timeouts++; throw new DOMException("timeout", "TimeoutError"); }) as typeof fetch), e => e instanceof SelsynError && e.code === "COMMAND_UNCERTAIN");
assert.equal(timeouts, 1, "comando físico nunca repetido automaticamente");
await assert.rejects(sendSelsynCommand("lock", "ABC1D23", "866557080755830", secret, responseFetch(Response.json({}))), e => e instanceof SelsynError && e.code === "COMMAND_UNCERTAIN");
const commandSql = readFileSync("supabase/migrations/20261019000000_selsyn_commands.sql", "utf8");
assert.ok(commandSql.includes("for update") && commandSql.includes("pg_advisory_xact_lock"));
assert.ok(commandSql.includes("'reserved','sending','accepted','unknown'"));
assert.ok(commandSql.includes("revoke all on public.selsyn_commands from public, anon, authenticated"));
assert.ok(commandSql.includes("current_setting('role', true)"));
const now = Date.parse("2026-10-06T20:00:00.000Z");
const safe = mapTrackedVehicle({ id: 123, identificador: "ABC1D23", bloqueioHabilitado: true, offLine: false, ultimaPosicao: { latitude: 0, longitude: 0, time: "2026-10-06T19:59:30.000Z", speed: 0, ignition: false } });
assert.doesNotThrow(() => validateLockSafety(safe, "ABC1D23", now));
assert.throws(() => validateLockSafety({ ...safe, lockEnabled: undefined }, "ABC1D23", now), /habilitado/);
assert.throws(() => validateLockSafety({ ...safe, position: { ...safe.position!, speed: 1 } }, "ABC1D23", now), /velocidade zero/);
assert.throws(() => validateLockSafety({ ...safe, position: { ...safe.position!, ignition: true } }, "ABC1D23", now), /ignição desligada/);
assert.throws(() => validateLockSafety({ ...safe, position: { ...safe.position!, time: "2026-10-06T19:58:00.000Z" } }, "ABC1D23", now), /60 segundos/);
assert.throws(() => validateLockSafety({ ...safe, position: undefined }, "ABC1D23", now), /60 segundos/);
assert.throws(() => validateLockSafety(safe, "XYZ1D23", now), /placa/);
// Reconciliação é GET com TOKEN, nunca PUT nem API Key como fallback.
const token = "token-autorizado-ficticio";
let executionGets = 0;
const commandFixture = { id: 2396, deviceId: 12345, type: { key: "UNLOCK" }, status: { key: "SENT" }, sendDate: "2026-10-06T19:54:30.574Z", returnDate: null, result: null, usuario: "PII descartada", dispositivo: { identificador: 866557080755830, rastreavel: { key: "916" } } };
const getExecution: typeof fetch = (async (url: string | URL | Request, init?: RequestInit) => {
  executionGets++;
  assert.equal(init?.method, "GET");
  assert.equal(new URL(String(url)).pathname, "/keek/rest/intervencao/comando/916/12345/UNLOCK");
  assert.equal(new Headers(init?.headers).get("x-r2f-auth"), token);
  assert.equal(new Headers(init?.headers).get("x-api-key"), null);
  assert.equal(new URL(String(url)).search, "");
  return Response.json(commandFixture);
}) as typeof fetch;
const execution = await getSelsynCommandExecution("916", "12345", "unlock", token, getExecution);
assert.equal(executionGets, 1);
assert.equal(execution.id, "2396"); assert.equal(execution.status, "SENT"); assert.equal(execution.returnedAt, null);
assert.ok(!JSON.stringify(execution).includes("usuario") && !JSON.stringify(execution).includes(token));
const expected = { id: "2396", deviceId: "12345", imei: "866557080755830", trackableId: "916", action: "unlock" as const, sentAt: "2026-10-06T19:54:30.574Z" };
assert.doesNotThrow(() => assertCommandExecution(execution, expected, now));
for (const mismatch of [{ ...execution, id: "2397" }, { ...execution, type: "LOCK" }, { ...execution, deviceId: "777" }, { ...execution, imei: "111" }, { ...execution, sentAt: "2026-10-05T19:54:30.574Z" }]) assert.throws(() => assertCommandExecution(mismatch, expected, now), SelsynError);
await assert.rejects(getSelsynCommandExecution("916", "12345", "unlock", "", getExecution), e => e instanceof SelsynError && e.code === "TOKEN_REQUIRED");
assert.equal(executionGets, 1, "sem token não faz request");
await assert.rejects(getSelsynCommandExecution("916", "12345", "unlock", token, responseFetch(new Response(token, { status: 403 }))), e => e instanceof SelsynError && e.code === "TOKEN_AUTH_FAILED" && !e.message.includes(token));
await assert.rejects(getSelsynCommandExecution("916", "12345", "unlock", token, responseFetch(new Response("x".repeat(33000)))), e => e instanceof SelsynError && e.code === "RESPONSE_TOO_LARGE");
await assert.rejects(getSelsynCommandExecution("916", "12345", "unlock", token, responseFetch(new Response("<html>"))), e => e instanceof SelsynError && e.code === "INVALID_PROVIDER_RESPONSE");
// Sessão: protocolo literal do JS público, sem rede real, sem credencial real e sem decodificar &#58; como ':'.
const fakeLogin = "usuario.teste", fakeSecret = "senha-ficticia";
assert.equal(Buffer.from(portalAuthorization(fakeLogin, fakeSecret), "base64").toString("latin1"), "usuario.teste&#58;senha-ficticia&#58;https://rastreame.com.br");
assert.throws(() => portalAuthorization("usuário", "senha😀"), SelsynError);
const futureAccess = "2026-10-07T13:30:00.000Z", futureLogin = "2026-10-08T13:00:00.000Z";
const portalSession = { accessToken: "access-token-ficticio", refreshToken: "refresh-token-ficticio", accessTokenExpireAt: futureAccess, loginExpireAt: futureLogin };
assert.deepEqual(parsePortalSession(portalSession, Date.parse("2026-10-07T13:00:00.000Z")), { accessToken: "access-token-ficticio", refreshToken: "refresh-token-ficticio", accessExpiresAt: futureAccess, loginExpiresAt: futureLogin });
assert.throws(() => parsePortalSession({ ...portalSession, accessTokenExpireAt: 1791336600 }), /formato validado/);
let authCalls = 0;
const authFetch: typeof fetch = (async (url: string | URL | Request, init?: RequestInit) => {
  authCalls++;
  assert.equal(String(url), "https://rastreame.com.br/auth/rest/login/v2/refresh/?versao=2000");
  assert.equal(init?.method, "POST"); assert.equal(init?.body, undefined); assert.equal(init?.redirect, "error");
  assert.equal(new Headers(init?.headers).get("authorization"), portalAuthorization(fakeLogin, "refresh-antigo"));
  return Response.json({ ...portalSession, accessTokenExpireAt: "2027-10-07T13:30:00.000Z", loginExpireAt: "2027-10-08T13:00:00.000Z", usuario: "PII descartada" });
}) as typeof fetch;
assert.equal((await authenticatePortal("refresh", fakeLogin, "refresh-antigo", authFetch)).refreshToken, "refresh-token-ficticio");
assert.equal(authCalls, 1, "refresh nunca é repetido automaticamente");
await assert.rejects(authenticatePortal("login", fakeLogin, fakeSecret, (async () => { throw new DOMException("timeout", "TimeoutError"); }) as typeof fetch), e => e instanceof SelsynError && e.code === "SESSION_ROTATION_UNCERTAIN");
await assert.rejects(authenticatePortal("login", fakeLogin, fakeSecret, responseFetch(Response.json({ accessToken: "x" }))), e => e instanceof SelsynError && e.code === "SESSION_RESPONSE_UNSUPPORTED");
const sessionSql = readFileSync("supabase/migrations/20261021000000_selsyn_session.sql", "utf8");
assert.ok(sessionSql.includes("lease_until > now()") && sessionSql.includes("revision=p_revision") && sessionSql.includes("ROTATION_UNCERTAIN"));
assert.ok(sessionSql.includes("revoke all on public.selsyn_session from public, anon, authenticated"));
let namespacedGets = 0;
const historyFetch: typeof fetch = (async (url: string | URL | Request, init?: RequestInit) => {
  namespacedGets++;
  assert.equal(init?.method, "GET");
  assert.equal(String(url), "https://rastreame.com.br/keek/rest/comando/12345");
  assert.equal(new Headers(init?.headers).get("x-r2f-ns"), "base-autorizada");
  return Response.json([{ ...commandFixture, id: 2397 }, commandFixture]);
}) as typeof fetch;
assert.equal((await getSelsynCommandFromHistory("12345", "2396", token, historyFetch, { portal: true, namespace: "base-autorizada" })).id, "2396");
assert.equal(namespacedGets, 1);
await assert.rejects(getSelsynCommandFromHistory("12345", "2396", token, responseFetch(Response.json([commandFixture, commandFixture])), { portal: true }), e => e instanceof SelsynError && e.code === "COMMAND_HISTORY_NOT_FOUND");
assert.ok(commandRoute.includes("getSelsynCommandExecution"));
assert.ok(commandRoute.includes("selsynExecutionCredentials"));
assert.ok(!commandRoute.includes('status: "confirmed"'), "sem enum terminal comprovado a reconciliação não libera comando novo");
const upgrade = readFileSync("supabase/migrations/20261020000000_selsyn_command_reconciliation.sql", "utf8");
assert.ok(upgrade.includes("add column if not exists provider_returned_at") && !/delete|truncate|drop table/i.test(upgrade));
console.log("✓ selsyn offline check ok (sem chamadas reais nem comandos físicos)");
