/** FIPE offline: contratos públicos reais como referência; mocks apenas neste teste. */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fipePath, fipeMonth, fipePrice, mapFipe, variation, fipeFleet } from "../src/lib/fipe";
import { inTestOrg } from "./test-org";
const root = join(__dirname, "..");
inTestOrg(async () => {
 assert.equal(fipePrice("R$ 118.358,00"), 118358);
 assert.equal(fipePrice("R$ 1.234.567,89"), 1234567.89);
 for(const v of ["R$ 0,00", "1200", "R$ 1,2", null]) assert.throws(() => fipePrice(v));
 assert.equal(fipeMonth("outubro/2026"), "2026-10");
 assert.equal(fipeMonth("março de 2026"), "2026-03");
 assert.throws(() => fipeMonth("desconhecido/2026"));
 assert.equal(fipePath("references", {}), "/references");
 const input = { type: "cars" as const, brandId: "25", modelId: "7693", yearId: "2020-5", reference: "338" };
 assert.equal(fipePath("detail", input), "/cars/brands/25/models/7693/years/2020-5?reference=338");
 assert.equal(fipePath("codeDetail", {type:"motorcycles",code:"811001-0",yearId:"32000-1"}), "/motorcycles/811001-0/years/32000-1");
 for(const p of [ {type:"cars",brandId:"../x"}, {type:"cars",reference:"x-api-key=secret"}, {type:"cars",yearId:"2020-9",code:"000001-0"} ]) assert.throws(() => fipePath("codeDetail", p as never));
 assert.throws(() => fipePath("plate", {}));
 assert.throws(() => fipePath("brands", {type:"cars",url:"https://evil.example"} as never));
 const raw = { vehicleType:1,price:"R$ 118.358,00",brand:"Honda",model:"Civic Sedan EXL 2.0 Flex",modelYear:2020,fuel:"Flex",fuelAcronym:"F",codeFipe:"014090-2",referenceMonth:"outubro de 2026" };
 const d = mapFipe("detail",raw); assert.ok(!Array.isArray(d));
 assert.equal(d.price,118358);assert.equal(d.referenceMonth,"2026-10");
 const h = mapFipe("history",{...raw,price:undefined,referenceMonth:undefined,priceHistory:[{month:"setembro de 2026",price:"R$ 118.904,00",reference:"337"}]});
 assert.ok(!Array.isArray(h));assert.equal(h.price,undefined);assert.equal(h.history[0].month,"2026-09");
 assert.throws(() => mapFipe("detail",{...raw,modelYear:0}));
 assert.throws(() => mapFipe("brands",{}));
 assert.deepEqual(variation(110,100),{amount:10,percent:10});assert.equal(variation(100,0),null);
 assert.deepEqual(fipeFleet([{status:"sold",fipePrice:500,fipeReferenceMonth:"2026-10"},{status:"available",fipePrice:100,fipeReferenceMonth:"2026-10"},{status:"rented"}]),{total:100,linked:1,applicable:2});
 const { fetchFipe, readFipeBody, publicFipeConfig } = await import("../src/lib/server/fipe");
 const token = "fake_fipe_token_only_for_test";
 let calls = 0;
 const send = (async (url: string | URL | Request, init?: RequestInit) => {
  calls++;assert.ok(String(url).startsWith("https://fipe.parallelum.com.br/api/v2/"));assert.ok(!String(url).includes(token));
  assert.equal((init?.headers as Record<string,string>)["X-Subscription-Token"],token);assert.equal(init?.redirect,"error");
  return Response.json(raw);
 }) as typeof fetch;
 const r=await fetchFipe("detail",input,token,send);assert.ok(!Array.isArray(r));assert.equal(r.price,118358);assert.equal(calls,1);
 for(const status of [401,403,404,429,500]) await assert.rejects(fetchFipe("brands",{type:"cars"},token,(async()=>Response.json({error:token},{status})) as typeof fetch),e=>e instanceof Error&&!e.message.includes(token) && "code" in e);
 await assert.rejects(fetchFipe("brands",{type:"cars"},token,(async()=>{const e=new Error(token);e.name="TimeoutError";throw e;}) as typeof fetch),e=>e instanceof Error && "code" in e && e.code==="FIPE_TIMEOUT");
 await assert.rejects(fetchFipe("brands",{type:"cars"},token,(async()=>new Response('<html>bad</html>')) as typeof fetch));
 await assert.rejects(readFipeBody(new Request("https://local.example",{method:"POST",body:"x".repeat(20000)})),/grande/);
 const c=publicFipeConfig({key_enc:token,key_last4:"TEST",enabled:false,auto_update:false,verified_at:null,generation:"x",last_error:null,cooldown_until:null,last_auto_at:null});assert.ok(!JSON.stringify(c).includes(token));
 for(const p of ["config","query","vehicles"])assert.ok(readFileSync(join(root,`src/app/api/fipe/${p}/route.ts`),'utf8').includes('await requireStaff()'));
 for(const p of ['fipe-picker','fipe-settings','vehicle-fipe-panel'])assert.ok(!readFileSync(join(root,`src/components/admin/${p}.tsx`),'utf8').includes('X-Subscription-Token'));
 const sql=readFileSync(join(root,'supabase/migrations/20261010000000_fipe.sql'),'utf8');assert.ok(sql.includes('unique(vehicle_id,fipe_code,year_id,reference_month)'));assert.ok(sql.includes('revoke all on public.%I from anon,authenticated'));
 console.log('✓ FIPE offline: paths, preços, referências, zero KM, DTOs, histórico, erros, token e autorização');
}).catch(e=>{console.error(e);process.exitCode=1});
