import type { TourDef } from "../../types";

/**
 * Tours por módulo, escritos para quem nunca usou um sistema de locadora.
 * Regras: só elementos que existem na tela; "click" apenas abre formulário vazio, aba ou detalhes (nunca salva);
 * passos marcados "quick" formam o Tour rápido.
 */
export const operacao: TourDef[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Entenda os indicadores, o período, o desempenho por veículo e os alertas.",
    kind: "modulo", module: "dashboard", route: "/admin", permission: "read", minutes: 3, version: 1,
    article: "primeiros-passos-visao-geral",
    keywords: ["dashboard", "painel", "indicadores", "resumo", "inicio", "kpi"],
    aliases: ["entender o dashboard", "o que significa cada numero", "tela inicial"],
    learn: ["ler os indicadores da frota e do dinheiro", "trocar o período analisado", "ver o desempenho de cada carro", "encontrar alertas e pendências"],
    next: "vehicles",
    steps: [
      { id: "intro", title: "Seu ponto de partida", content: "O Dashboard é o seu ponto de partida. Aqui você acompanha um resumo da operação e identifica rapidamente o que precisa da sua atenção. Nada nesta tela altera dados: é só leitura.", target: "dashboard-header", quick: true },
      { id: "onboarding", title: "Primeiros passos", content: "Enquanto a configuração não estiver completa, este quadro mostra o que falta: dados da empresa, logo, primeiro veículo, pagamentos e contrato. Clique em cada item para ir direto à tela certa. Ele some quando tudo estiver pronto.", target: "dashboard-onboarding", optional: true, article: "onboarding-checklist-locadora" },
      { id: "period", title: "Período analisado", content: "Escolha o período dos números financeiros: hoje, esta semana, este mês, meses anteriores ou datas personalizadas. Use para comparar meses ou fechar o caixa do período.", target: "dashboard-period", quick: true },
      { id: "fleet", title: "Frota e operação", content: "Esta linha mostra quanto foi investido na frota, quantos carros estão disponíveis e alugados, quantas locações estão ativas e quantas reservas existem. Use para saber, num relance, se há carro parado.", target: "dashboard-kpis-fleet", quick: true },
      { id: "money", title: "Dinheiro do período", content: "Faturamento recebido, locações perto de vencer, valores em atraso, multas e lucro líquido no período escolhido. Valor em atraso alto é sinal para cobrar em Pagamentos.", target: "dashboard-kpis-finance", quick: true },
      { id: "vehicles", title: "Desempenho por veículo", content: "Cada carro com quanto custou, quanto faturou, os custos e o lucro, além do aviso de troca de óleo. Clique em um carro para abrir a Visão 360°, com o histórico completo dele.", target: "dashboard-vehicles", article: "visao-360-veiculo" },
      { id: "charts", title: "Gráficos", content: "Receitas contra despesas mês a mês, ocupação da frota, locações por mês e despesas por categoria. Ajudam a perceber tendências, como meses mais fracos ou gastos subindo.", target: "dashboard-charts" },
      { id: "alerts", title: "Alertas e próximas reservas", content: "Vencimentos e pendências que pedem ação aparecem aqui; clique para ir ao registro. Ao lado ficam as próximas reservas e as locações recentes. O sino no topo reúne esses avisos em qualquer tela.", target: "dashboard-alerts", quick: true },
    ],
  },
  {
    id: "requests",
    title: "Solicitações",
    description: "Como conferir e responder pedidos de locação feitos pelo aplicativo.",
    kind: "modulo", module: "solicitacoes", route: "/admin/requests", permission: "operate", feature: "tenant_app", minutes: 3, version: 1,
    article: "aprovar-solicitacao-locacao",
    keywords: ["solicitacao", "pedido", "aprovar", "recusar", "app", "documentos"],
    aliases: ["aprovar pedido de locacao", "pedido pelo aplicativo", "cliente pediu carro pelo app"],
    learn: ["onde chegam os pedidos do aplicativo", "filtrar por situação", "conferir documentos", "aprovar, recusar ou pedir ajuste"],
    next: "rentals",
    steps: [
      { id: "intro", title: "Pedidos do aplicativo", content: "Quando um cliente pede um carro pelo aplicativo da {org}, o pedido chega aqui com os documentos anexados. Você decide: aprovar, recusar ou pedir que ele corrija algo.", target: "requests-header", quick: true },
      { id: "kpis", title: "Resumo", content: "Quantos pedidos aguardam sua análise, quantos viraram locação e quantos foram recusados. \"Aguardando análise\" maior que zero significa cliente esperando resposta.", target: "requests-kpis" },
      { id: "filters", title: "Filtrar por situação", content: "Use Pendentes para ver só o que precisa de resposta. Aprovadas, Não aprovadas e Todas servem para consultar o histórico.", target: "requests-filters", quick: true },
      { id: "list", title: "Lista de pedidos", content: "Cada linha mostra cliente, carro pretendido, período, plano e situação. Os status são: Em análise, Aprovada, Não aprovada e Ajuste solicitado.", target: "requests-list" },
      { id: "open", title: "Analisar e aprovar", content: "Este botão abre o pedido com os dados do cliente e as fotos da CNH, comprovante de residência e selfie. Ao aprovar, você confirma valor da parcela, caução e modelo de contrato; o sistema cria a locação e o contrato. Não vamos aprovar nada neste treinamento.", target: "requests-open", optional: true, quick: true },
    ],
  },
  {
    id: "rentals",
    title: "Locações",
    description: "Treinamento completo de locações: lista, nova locação, cobrança, contrato, vistorias e finalização.",
    kind: "modulo", module: "locacoes", route: "/admin/rentals", permission: "read", minutes: 7, version: 1,
    article: "criar-locacao-contrato",
    keywords: ["locacao", "aluguel", "contrato", "parcela", "caucao", "vistoria", "devolucao", "entrega"],
    aliases: ["como alugar um carro", "nova locacao", "como fazer uma locacao", "registrar aluguel", "finalizar locacao"],
    learn: ["consultar e filtrar as locações", "criar uma locação com cobrança", "entender caução e quilometragem", "gerar e enviar o contrato", "registrar entrega e devolução"],
    next: "payments",
    steps: [
      { id: "intro", chapter: "Conhecendo a tela", title: "O que é uma locação", content: "Uma locação é o aluguel de um carro para um cliente por um período. Ela reúne quem alugou, qual veículo, as datas, o valor das parcelas, a caução e a quilometragem. É o centro da operação.", target: "rentals-header", quick: true },
      { id: "kpis", chapter: "Conhecendo a tela", title: "Resumo das locações", content: "Locações ativas, atrasadas, total já recebido e valor em atraso. Uma locação fica Atrasada quando passa da data de devolução sem ser finalizada.", target: "rentals-kpis" },
      { id: "search", chapter: "Conhecendo a tela", title: "Encontrar uma locação", content: "Digite o nome do cliente ou a placa do carro. Use os filtros de Status (Ativa, Atrasada, Finalizada, Cancelada, Pendente) e de tipo de contrato quando quiser ver um grupo específico.", target: "rentals-search", quick: true },
      { id: "table", chapter: "Conhecendo a tela", title: "Lista", content: "Cada linha mostra locatário, veículo, período, valor da parcela, quanto já foi recebido, quanto está em atraso e o status. Clique em uma linha para abrir todos os detalhes.", target: "rentals-table" },
      { id: "new", chapter: "Criando uma locação", title: "Nova locação", content: "Para alugar um carro, clique em Nova locação. Antes, cliente e veículo precisam estar cadastrados. Vamos abrir o formulário só para conhecer; nada será salvo.", target: "rentals-new", quick: true },
      { id: "form", chapter: "Criando uma locação", title: "Cliente, carro e datas", content: "Escolha o locatário e o veículo pela placa, o tipo de contrato (semanal, quinzenal, mensal ou diária), o status e as datas e horários de início e fim. Campos com * são obrigatórios.", target: "rentals-form", click: "rentals-new", dialog: true },
      { id: "billing", chapter: "Criando uma locação", title: "Cobrança", content: "Defina a periodicidade e o valor de cada parcela, a primeira e a última cobrança, multa e juros por atraso, dias de carência e dia de pagamento. O sistema gera as parcelas sozinho. Se marcar o envio automático, o cliente recebe a cobrança com PIX antes do vencimento.", target: "rentals-form-billing", click: "rentals-new", dialog: true },
      { id: "deposit", chapter: "Criando uma locação", title: "Caução e quilometragem", content: "Caução é o valor de garantia que o cliente deixa e recebe de volta no fim, se estiver tudo certo. KM inicial e KM final são a quilometragem do painel na entrega e na devolução. Para não salvar, feche o formulário com Cancelar.", target: "rentals-form", click: "rentals-new", dialog: true },
      { id: "detail", chapter: "Contrato", route: "/admin/rentals/[id]", via: "/admin/rentals", click: "rentals-view", title: "Detalhes da locação", content: "Ao abrir uma locação você vê status, total recebido, valor em atraso e quilometragem rodada, mais Imprimir e Editar no topo.", target: "rental-detail-header", optional: true },
      { id: "installments", chapter: "Pagamento", title: "Parcelas", content: "Cada parcela aparece como Pago, Atrasado ou A receber, já com multa e juros quando vencida. O ícone ao lado envia a cobrança com PIX ou o comprovante. Para dar baixa com valor e forma de pagamento, use a tela Pagamentos.", target: "rental-detail-installments", optional: true, article: "detalhes-locacao-gestao" },
      { id: "contract", chapter: "Contrato", title: "Contrato e assinatura", content: "Gere o contrato com os dados da locação. Com a Autentique ativa, use 'Enviar para assinatura' e acompanhe aqui status, signatários e PDF assinado. Sem ela, o cliente assina pelo link com CPF, selfie e assinatura desenhada.", target: "rental-detail-contract", optional: true, article: "gerar-assinar-contrato" },
      { id: "inspections", chapter: "Finalização", title: "Vistorias de entrega e devolução", content: "Registrar a entrega coloca a locação como Ativa e o carro como Alugado. Registrar a devolução finaliza a locação e deixa o carro Disponível de novo. Cada vistoria tem quilometragem, combustível, checklist de avarias e assinatura do cliente.", target: "rental-detail-inspections", optional: true, quick: true, article: "vistoria-entrega-devolucao" },
    ],
  },
  {
    id: "reservations",
    title: "Reservas",
    description: "Reservar um carro para datas futuras sem conflito de agenda.",
    kind: "modulo", module: "reservas", route: "/admin/reservations", permission: "read", feature: "reservations", minutes: 3, version: 1,
    article: "criar-reserva",
    keywords: ["reserva", "agenda", "calendario", "datas", "disponibilidade"],
    aliases: ["reservar carro", "agendar locacao", "ver agenda da frota"],
    learn: ["a diferença entre reserva e locação", "ver a agenda em lista ou calendário", "criar uma reserva", "entender os status"],
    next: "clients",
    steps: [
      { id: "intro", title: "Reserva x locação", content: "A reserva separa um carro para um cliente em datas futuras. Ela ainda não é aluguel: não gera parcelas nem contrato. Quando o cliente retirar o carro, crie a locação em Locações.", target: "reservations-header", quick: true },
      { id: "view", title: "Lista ou calendário", content: "Alterne entre a lista e o calendário do mês. O calendário ajuda a enxergar quais dias cada carro já está comprometido.", target: "reservations-view", quick: true },
      { id: "filters", title: "Filtrar", content: "Busque pelo cliente ou placa e filtre por status ou por veículo. Status: Pendente, Confirmada, Concluída e Cancelada.", target: "reservations-filters", optional: true },
      { id: "new", title: "Nova reserva", content: "Clique para reservar. Vamos abrir o formulário só para conhecer.", target: "reservations-new", quick: true },
      { id: "form", title: "Dados da reserva", content: "Escolha o cliente, o carro pela placa, as datas inicial e final, o status e, se quiser, o modelo de contrato. Ao salvar, o sistema recusa datas que batem com outra reserva ou com uma locação do mesmo carro. Feche com Cancelar para não salvar.", target: "reservations-form", click: "reservations-new", dialog: true, quick: true },
    ],
  },
  {
    id: "vehicles",
    title: "Veículos",
    description: "Treinamento completo da frota: lista, busca, cadastro campo a campo, fotos e documento.",
    kind: "modulo", module: "veiculos", route: "/admin/vehicles", permission: "read", minutes: 5, version: 1,
    article: "cadastrar-veiculo",
    keywords: ["veiculo", "carro", "moto", "frota", "placa", "cadastro", "crlv", "fipe", "hodometro"],
    aliases: ["cadastrar carro", "adicionar veiculo", "colocar carro no sistema", "cadastrar moto", "ver minha frota"],
    learn: ["consultar sua frota", "pesquisar e filtrar veículos", "entender os status", "cadastrar um veículo", "anexar fotos e documento"],
    next: "clients",
    steps: [
      { id: "intro", chapter: "Conhecendo a tela", title: "Sua frota", content: "Aqui ficam todos os carros e motos da {org}. Cada veículo cadastrado pode ser alugado, reservado, receber manutenção e multas. Comece cadastrando a frota.", target: "vehicles-header", quick: true },
      { id: "search", chapter: "Conhecendo a tela", title: "Pesquisar", content: "Digite placa, marca ou modelo para achar um carro. Ao lado, filtre por status ou tipo.", target: "vehicles-search", quick: true },
      { id: "status", chapter: "Conhecendo a tela", title: "Entenda os status", content: "Disponível: pronto para alugar. Alugado: com cliente. Reservado: separado para datas futuras. Manutenção: na oficina. Vendido: saiu da frota, mas o histórico continua.", target: "vehicles-filters" },
      { id: "table", chapter: "Conhecendo a tela", title: "Lista e ações", content: "Veja placa, hodômetro, vencimento do licenciamento, valor de compra e status. Os ícones de cada linha abrem os detalhes, editam ou excluem. Excluir pede confirmação.", target: "vehicles-row-actions", optional: true },
      { id: "new", chapter: "Cadastrando", title: "Novo veículo", content: "Use este botão para adicionar um carro ou uma moto. Vamos abrir o formulário só para conhecer; nada será salvo.", target: "vehicles-new", quick: true },
      { id: "crlv", chapter: "Cadastrando", title: "Atalho: importar o CRLV-e", content: "Se tiver o documento digital do veículo (CRLV-e em PDF ou foto), anexe aqui e o sistema tenta preencher os campos sozinho. Sempre confira o resultado.", target: "vehicles-form-crlv", click: "vehicles-new", dialog: true },
      { id: "data", chapter: "Cadastrando", title: "Dados do veículo", content: "Placa, tipo, marca, modelo, ano de fabricação e hodômetro são obrigatórios. Hodômetro é a quilometragem atual mostrada no painel. Renavam, chassi, cor, licenciamento, data e valor de compra são opcionais, mas ajudam nos relatórios e alertas.", target: "vehicles-form", click: "vehicles-new", dialog: true, quick: true },
      { id: "fipe", chapter: "Cadastrando", title: "Tabela FIPE", content: "FIPE é a tabela de preço médio de veículos no Brasil. Busque a versão do carro para guardar o valor de referência e acompanhar quanto a frota vale. A consulta automática pela placa não está disponível; use a FIPE ou preencha à mão.", target: "vehicles-form-fipe", click: "vehicles-new", dialog: true },
      { id: "photos", chapter: "Fotos e documento", title: "Fotos do veículo", content: "Adicione fotos do carro. Elas aparecem nos detalhes e ajudam a identificar o veículo.", target: "vehicles-form-photos", click: "vehicles-new", dialog: true },
      { id: "document", chapter: "Fotos e documento", title: "Documento (CRLV)", content: "Anexe o documento do veículo para tê-lo sempre à mão. Para sair sem salvar, clique em Cancelar no formulário.", target: "vehicles-form-document", click: "vehicles-new", dialog: true },
    ],
  },
  {
    id: "monitoring",
    title: "Rastreamento",
    description: "Consultar posição, histórico e sensores dos veículos com rastreador Selsyn.",
    kind: "modulo", module: "rastreamento", route: "/admin/monitoring", permission: "read", feature: "tracking", minutes: 2, version: 1,
    article: "monitoramento-frota-selsyn",
    keywords: ["rastreamento", "rastreador", "mapa", "gps", "selsyn", "localizacao"],
    aliases: ["onde esta o carro", "ver carro no mapa", "localizar veiculo"],
    learn: ["conferir se o rastreamento está ativo", "sincronizar a frota", "usar as abas de consulta"],
    next: "clients",
    steps: [
      { id: "intro", title: "Onde estão seus carros", content: "Se a {org} usa rastreador Selsyn, esta tela mostra os veículos no mapa e permite consultar histórico, sensores, alertas e relatórios. Só consulta: nenhum comando é enviado ao carro.", target: "monitoring-header", quick: true },
      { id: "status", title: "Situação da conexão", content: "Mostra se o rastreamento está configurado. Se aparecer \"Não configurado\", a credencial do fornecedor ainda não foi cadastrada pela equipe técnica.", target: "monitoring-status", quick: true },
      { id: "sync", title: "Sincronizar", content: "Busca no fornecedor a lista de rastreadores e a última posição de cada um. Depois aparecem os totais (em movimento, parados, offline) e o mapa.", target: "monitoring-actions" },
      { id: "tabs", title: "Abas de consulta", content: "Frota e mapa, Histórico, Sensores, Alertas e Relatórios são consultas ao fornecedor. Em Vínculos você liga cada rastreador ao carro cadastrado aqui.", target: "monitoring-tabs", quick: true },
    ],
  },
  {
    id: "clients",
    title: "Clientes",
    description: "Cadastro de locatários campo a campo: documento, CNH, contatos e endereço.",
    kind: "modulo", module: "clientes", route: "/admin/clients", permission: "read", minutes: 4, version: 1,
    article: "cadastrar-cliente",
    keywords: ["cliente", "locatario", "motorista", "cnh", "cpf", "cadastro", "endereco"],
    aliases: ["cadastrar cliente", "adicionar locatario", "cadastrar motorista"],
    learn: ["pesquisar clientes", "acompanhar a validade da CNH", "cadastrar um cliente completo", "ver o histórico de locações"],
    next: "rentals",
    steps: [
      { id: "intro", title: "Seus locatários", content: "Cada pessoa ou empresa que aluga um carro precisa estar cadastrada aqui. O cadastro alimenta contratos, cobranças e o aplicativo do cliente.", target: "clients-header", quick: true },
      { id: "search", title: "Pesquisar", content: "Busque por nome, CPF ou CNPJ, telefone, cidade ou e-mail.", target: "clients-search", quick: true },
      { id: "filters", title: "Situação da CNH", content: "Filtre clientes com CNH válida, a vencer ou vencida. Use antes de renovar um contrato: CNH vencida é risco para a locadora.", target: "clients-filters" },
      { id: "actions", title: "Ver, editar ou excluir", content: "Abra os detalhes para ver a CNH anexada e o histórico de locações daquele cliente.", target: "clients-row-actions", optional: true },
      { id: "new", title: "Novo cliente", content: "Clique para cadastrar. Vamos abrir o formulário só para conhecer.", target: "clients-new", quick: true },
      { id: "identity", title: "1. Identificação", content: "Escolha Pessoa Física (CPF) ou Jurídica (CNPJ). Documento e nome são obrigatórios. Use exatamente o CPF do contrato: é ele que liga o cliente ao aplicativo.", target: "clients-form-identity", click: "clients-new", dialog: true, quick: true },
      { id: "cnh", title: "2. Habilitação", content: "Número, categoria e vencimento da CNH, e o PDF da CNH Digital. O vencimento gera alertas antes de expirar.", target: "clients-form-cnh", click: "clients-new", dialog: true },
      { id: "contacts", title: "4. Contatos", content: "O telefone principal (WhatsApp) é obrigatório: é por ele que saem contratos e cobranças. O e-mail também recebe contrato e comprovantes.", target: "clients-form-contacts", click: "clients-new", dialog: true, quick: true },
      { id: "address", title: "5. Endereço", content: "Digite o CEP para preencher o endereço automaticamente. Observações internas não aparecem para o cliente. Feche com Cancelar para não salvar.", target: "clients-form-address", click: "clients-new", dialog: true },
    ],
  },
  {
    id: "payments",
    title: "Pagamentos",
    description: "Cobrar, dar baixa e acompanhar todas as parcelas das locações.",
    kind: "modulo", module: "pagamentos", route: "/admin/pagamentos", permission: "finance", feature: "payments", minutes: 5, version: 1,
    article: "visao-geral-pagamentos",
    keywords: ["pagamento", "parcela", "cobranca", "baixa", "pix", "comprovante", "receber", "boleto"],
    aliases: ["como cobrar o cliente", "dar baixa em pagamento", "receber pagamento", "parcela atrasada"],
    learn: ["ler o resumo de recebimentos", "filtrar parcelas por status e vencimento", "entender cada status", "dar baixa, editar, cobrar e outras ações"],
    next: "finance",
    steps: [
      { id: "intro", title: "Todas as parcelas", content: "Cada locação gera parcelas. Aqui estão todas elas, de todos os clientes, para você cobrar e registrar o recebimento.", target: "payments-header", quick: true },
      { id: "kpis", title: "Resumo", content: "Quanto está em aberto, quanto já foi recebido, quanto venceu e o total. O valor Vencido é o que precisa de cobrança agora.", target: "payments-kpis", quick: true },
      { id: "filters", title: "Encontrar parcelas", content: "Busque por cliente, CPF, placa ou contrato. Ordene por prioridade (vencidos primeiro) e filtre por status e vencimento: hoje, amanhã, vencidos ou futuros. Use \"Vencendo hoje\" toda manhã.", target: "payments-filters", quick: true },
      { id: "status", title: "Entenda os status", content: "Em aberto: ainda não venceu. Vencido: passou da data sem pagamento. Em análise: o cliente enviou comprovante e aguarda sua conferência. Pago: recebido. Cancelado: não será mais cobrado.", target: "payments-list", optional: true },
      { id: "actions", title: "Ações da parcela", content: "Dar baixa registra o recebimento (valor, data e forma). Editar ajusta valor ou vencimento. Cobrar envia a cobrança pelos meios ativos. Mais traz cancelar, excluir, recibo e opções de InfinitePay e Asaas. Nenhuma delas é executada neste treinamento.", target: "payments-card-actions", optional: true, quick: true, article: "dar-baixa-pagamento" },
      { id: "methods", title: "Formas de receber", content: "PIX manual: o cliente paga na sua chave e envia o comprovante; sua equipe confere e aprova. Asaas: gera PIX, boleto ou cartão e dá baixa sozinho quando o pagamento cai. InfinitePay: aproximação no celular ou link de pagamento. As formas ativas são escolhidas em Configurações > Pagamentos.", article: "configurar-meios-pagamento" },
    ],
  },
  {
    id: "finance",
    title: "Financeiro",
    description: "Interpretar receitas, despesas, saldo e pendências.",
    kind: "modulo", module: "financeiro", route: "/admin/finance", permission: "finance", feature: "finance", minutes: 3, version: 1,
    article: "visao-geral-financeiro",
    keywords: ["financeiro", "receita", "despesa", "saldo", "caixa", "lucro"],
    aliases: ["ver saldo", "quanto entrou", "fluxo de caixa"],
    learn: ["conferir comprovantes enviados pelos clientes", "ler receitas, despesas e saldo", "encontrar o que falta receber e pagar"],
    next: "expenses",
    steps: [
      { id: "intro", title: "O dinheiro da locadora", content: "Resumo de quanto entrou, quanto saiu e o saldo, mês a mês. Escolha no topo o período de 3, 6 ou 12 meses.", target: "finance-header", quick: true },
      { id: "receipts", title: "Comprovantes para conferir", content: "Quando o cliente envia comprovante de PIX pelo aplicativo, ele aparece aqui. A parcela só fica paga depois que você confere no extrato e aprova.", target: "finance-receipts", optional: true, quick: true, article: "aprovar-comprovante-pix" },
      { id: "kpis", title: "Indicadores", content: "Receitas recebidas, despesas (incluindo manutenção), saldo, recebimentos pendentes (vencidos e não pagos) e despesas ainda não pagas.", target: "finance-kpis", quick: true },
      { id: "charts", title: "Comparativo mensal", content: "Barras de receitas contra despesas por mês e o fluxo do saldo acumulado. Saldo caindo mês a mês pede atenção aos gastos ou à inadimplência.", target: "finance-charts" },
      { id: "pending", title: "Pendências", content: "Lista do que falta receber e do que falta pagar, para você agir em Pagamentos ou Despesas.", target: "finance-pending" },
    ],
  },
  {
    id: "expenses",
    title: "Despesas",
    description: "Registrar gastos da operação e da frota.",
    kind: "modulo", module: "despesas", route: "/admin/expenses", permission: "finance", feature: "finance", minutes: 3, version: 1,
    article: "cadastrar-despesa",
    keywords: ["despesa", "gasto", "conta", "fornecedor", "custo"],
    aliases: ["lancar despesa", "registrar gasto", "cadastrar conta a pagar"],
    learn: ["ver os totais de despesas", "filtrar por categoria, mês e pagamento", "lançar uma despesa"],
    next: "maintenance",
    steps: [
      { id: "intro", title: "Gastos da operação", content: "Registre aqui o que a {org} gasta: seguro, IPVA, aluguel, combustível, peças. As despesas entram no saldo do Financeiro e, quando ligadas a uma placa, no lucro daquele carro.", target: "expenses-header", quick: true },
      { id: "kpis", title: "Totais", content: "Recorrentes são gastos que se repetem todo mês; diversas são pontuais. \"A pagar\" soma o que ainda não foi pago.", target: "expenses-kpis" },
      { id: "filters", title: "Filtrar", content: "Busque por descrição, fornecedor ou placa e filtre por categoria, mês ou situação do pagamento.", target: "expenses-filters", quick: true },
      { id: "new", title: "Nova despesa", content: "Clique para lançar. Vamos abrir o formulário só para conhecer.", target: "expenses-new", quick: true },
      { id: "form", title: "Dados da despesa", content: "Descrição, data e valor são obrigatórios. Deixe a placa em branco para um gasto da frota toda. Marque Pago quando já tiver pago. Feche com Cancelar para não salvar.", target: "expenses-form", click: "expenses-new", dialog: true, quick: true },
    ],
  },
  {
    id: "maintenance",
    title: "Manutenção",
    description: "Histórico e agenda de manutenções, com aviso de troca de óleo.",
    kind: "modulo", module: "manutencao", route: "/admin/maintenance", permission: "read", feature: "maintenance", minutes: 3, version: 1,
    article: "cadastrar-manutencao",
    keywords: ["manutencao", "oficina", "oleo", "revisao", "pneu", "conserto"],
    aliases: ["registrar manutencao", "troca de oleo", "carro na oficina", "agendar revisao"],
    learn: ["acompanhar pendentes, agendadas e realizadas", "registrar uma manutenção", "manter o aviso de troca de óleo correto"],
    next: "fines",
    steps: [
      { id: "intro", title: "Cuidados com a frota", content: "Registre cada serviço feito ou agendado nos carros. Assim você não perde prazos e sabe quanto cada veículo custa.", target: "maintenance-header", quick: true },
      { id: "kpis", title: "Situação", content: "Pendentes, próximas (agendadas), realizadas e o custo total. Status: Agendada, Pendente e Realizada.", target: "maintenance-kpis" },
      { id: "table", title: "Lista", content: "Data, placa, descrição, KM atual, próxima KM e valor. Se o carro estiver com um cliente, aparece o botão para avisá-lo da manutenção.", target: "maintenance-table", quick: true },
      { id: "new", title: "Nova manutenção", content: "Clique para registrar. Vamos abrir o formulário só para conhecer.", target: "maintenance-new", quick: true },
      { id: "form", title: "Dados do serviço", content: "Placa, data e descrição são obrigatórios. Para o aviso de troca de óleo funcionar, escreva óleo ou revisão na descrição, preencha a Próxima KM e marque como Realizada. Feche com Cancelar para não salvar.", target: "maintenance-form", click: "maintenance-new", dialog: true, quick: true },
    ],
  },
  {
    id: "fines",
    title: "Multas",
    description: "Prazos de identificação do condutor, vencimentos e pagamento de multas.",
    kind: "modulo", module: "multas", route: "/admin/fines", permission: "read", feature: "fines", minutes: 4, version: 1,
    article: "gerenciar-multas-transito",
    keywords: ["multa", "infracao", "autuacao", "condutor", "detran", "vencimento"],
    aliases: ["cadastrar multa", "indicar condutor", "multa de transito"],
    learn: ["acompanhar prazos de multas", "entender os status", "cadastrar uma multa com os prazos certos"],
    next: "notes",
    steps: [
      { id: "intro", title: "Multas da frota", content: "Quando chega uma multa de um carro da {org}, registre aqui para não perder o prazo de indicar quem dirigia e o prazo do desconto.", target: "fines-header", quick: true },
      { id: "kpis", title: "Resumo", content: "Multas em aberto, valor total em aberto, quantas aguardam identificação do condutor e quantas vencem em 15 dias.", target: "fines-kpis", quick: true },
      { id: "alerts", title: "Alertas de vencimento", content: "Multas com prazo próximo aparecem destacadas aqui.", target: "fines-alerts", optional: true },
      { id: "status", title: "Entenda os status", content: "Pendente: aguardando pagamento. Identificar condutor: indique quem dirigia dentro do prazo. Pago. Vencida: passou do vencimento sem pagamento. Contestada: está em recurso.", target: "fines-filters" },
      { id: "new", title: "Nova multa", content: "Clique para cadastrar. Vamos abrir o formulário só para conhecer.", target: "fines-new" },
      { id: "form", title: "Dados da multa", content: "Placa, número do auto de infração, descrição, data da autuação, vencimento e valor são obrigatórios. Locatário é quem estava com o carro; real infrator é quem dirigia, se for outra pessoa. A data da autuação já sugere o limite de identificação (30 dias). Feche com Cancelar.", target: "fines-form", click: "fines-new", dialog: true, quick: true },
    ],
  },
  {
    id: "notes",
    title: "Anotações",
    description: "Diário da operação: combinados, ocorrências e lembretes.",
    kind: "modulo", module: "anotacoes", route: "/admin/notes", permission: "read", minutes: 2, version: 1,
    article: "registro-anotacoes-ocorrencias",
    keywords: ["anotacao", "nota", "registro", "ocorrencia", "lembrete", "diario"],
    aliases: ["fazer uma anotacao", "registrar combinado com cliente"],
    learn: ["registrar combinados com data e hora", "filtrar anotações por cliente"],
    next: "reports",
    steps: [
      { id: "intro", title: "Diário da operação", content: "Registre combinados, reclamações e lembretes com data e hora, ligados a um cliente ou gerais. É a memória da equipe.", target: "notes-header", quick: true },
      { id: "filters", title: "Buscar", content: "Pesquise pelo texto ou escolha um locatário para ver só as anotações dele.", target: "notes-filters", quick: true },
      { id: "timeline", title: "Linha do tempo", content: "As anotações aparecem agrupadas por dia, da mais recente para a mais antiga. Passe o mouse sobre uma para editar ou excluir.", target: "notes-timeline", optional: true },
      { id: "new", title: "Nova anotação", content: "Data, horário e descrição são obrigatórios; o locatário é opcional. Vamos abrir só para conhecer. Feche com Cancelar.", target: "notes-form", click: "notes-new", dialog: true, quick: true },
    ],
  },
  {
    id: "incidents",
    title: "App do locatário",
    description: "Responder ocorrências e conferir documentos enviados pelos clientes no aplicativo.",
    kind: "modulo", module: "ocorrencias", route: "/admin/incidents", permission: "read", feature: "tenant_app", minutes: 3, version: 1,
    article: "conferir-ocorrencias-documentos",
    keywords: ["app", "aplicativo", "ocorrencia", "documento", "cnh", "pneu", "pane"],
    aliases: ["cliente relatou problema", "conferir documento do cliente", "aplicativo do cliente"],
    learn: ["onde chegam os problemas relatados no app", "responder e atualizar uma ocorrência", "aprovar ou recusar documentos"],
    next: "security",
    steps: [
      { id: "intro", title: "O que vem do aplicativo", content: "Seus clientes usam o aplicativo da {org} para pagar parcelas, fazer vistoria, relatar problemas e enviar documentos. Esta tela recebe os problemas relatados e os documentos para você conferir.", target: "incidents-header", quick: true },
      { id: "tabs", title: "Ocorrências e Documentos", content: "O número ao lado de cada aba mostra quantos itens aguardam você.", target: "incidents-tabs", quick: true },
      { id: "list", title: "Ocorrências", content: "Pneu furado, pane, acidente, luz no painel e outros, com descrição e fotos. Em Atualizar você muda o status (Aberta, Em análise, Em atendimento, Aguardando você, Resolvida, Cancelada) e responde; o cliente é avisado no celular.", target: "incidents-list", click: "incidents-tab-ocorrencias" },
      { id: "docs", title: "Documentos", content: "CNH frente e verso e comprovante de endereço enviados pelo cliente. Confira e aprove, ou recuse informando o motivo, que vai para o cliente.", target: "incidents-documents", click: "incidents-tab-documentos", quick: true },
    ],
  },
  {
    id: "security",
    title: "Segurança",
    description: "Sinais de uso do aplicativo pelos clientes, aparelhos e registro de ações.",
    kind: "modulo", module: "seguranca", route: "/admin/security", permission: "settings", feature: "tenant_app", minutes: 2, version: 1,
    article: "seguranca-antifraude-app",
    keywords: ["seguranca", "antifraude", "risco", "aparelho", "auditoria"],
    aliases: ["cliente suspeito", "ver aparelhos do cliente", "historico de acoes"],
    learn: ["ler o nível de atenção de cada cliente", "ver aparelhos cadastrados", "consultar o registro de ações"],
    next: "reports",
    steps: [
      { id: "intro", title: "Acompanhar com calma", content: "Esta área ajuda você a acompanhar sinais de uso do aplicativo nos últimos 30 dias. É uma orientação para conferência: nenhum cliente é bloqueado e um sinal não significa fraude.", target: "security-header", quick: true },
      { id: "risk", title: "Clientes por nível de atenção", content: "Cada cliente recebe um nível: Baixo, Atenção, Elevado ou Crítico, a partir de sinais como muitos aparelhos ou acessos diferentes. Clique para ver os detalhes antes de tirar conclusões.", target: "security-risk", quick: true },
      { id: "devices", title: "Aparelhos", content: "Celulares registrados pelo aplicativo e se recebem notificações.", target: "security-devices" },
      { id: "audit", title: "Registro de ações", content: "Últimas ações feitas pelo aplicativo e pela equipe, com data e IP.", target: "security-audit" },
    ],
  },
  {
    id: "reports",
    title: "Relatórios",
    description: "Gerar, interpretar, imprimir e exportar relatórios.",
    kind: "modulo", module: "relatorios", route: "/admin/reports", permission: "read", feature: "reports", minutes: 3, version: 1,
    article: "relatorios-exportacao-csv",
    keywords: ["relatorio", "exportar", "planilha", "excel", "csv", "imprimir"],
    aliases: ["gerar relatorio", "exportar para excel", "baixar planilha"],
    learn: ["escolher o tipo de relatório", "filtrar por período, veículo e status", "imprimir e exportar"],
    next: "settings-empresa",
    steps: [
      { id: "intro", title: "Relatórios", content: "Escolha um assunto, filtre e veja gráfico, totais e tabela. Ideal para fechar o mês ou levar à contabilidade.", target: "reports-header", quick: true },
      { id: "types", title: "Tipo de relatório", content: "Frota, Locações, Receitas, Despesas, Manutenção, Multas e Reservas.", target: "reports-types", quick: true },
      { id: "filters", title: "Filtros", content: "Escolha um mês ou um período (De/Até), um veículo e um status. Limpar filtros volta ao padrão.", target: "reports-filters", quick: true },
      { id: "chart", title: "Gráfico e totais", content: "O gráfico resume o relatório e os totais mostram registros e valores do filtro atual.", target: "reports-chart" },
      { id: "export", title: "Imprimir ou exportar", content: "Imprimir gera uma versão limpa (também serve para salvar em PDF pelo navegador). Exportar CSV baixa a planilha para Excel.", target: "reports-actions", quick: true },
    ],
  },
];
